-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers_by_country
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers_by_country DESC;


-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers_by_gender DESC;


-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_products_by_category DESC;


-- What is the average costs in each category?
SELECT
	category,
	AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- What is the total revenue generated for each category?
SELECT
	dp.category,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;



-- Find total revenue that is generated by each customer
SELECT
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
	ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries?
SELECT
	dc.country,
	SUM(fs.quantity) AS quantity
FROM gold.fact_sales AS fs
INNER JOIN gold.dim_customers AS dc
	ON fs.customer_key = dc.customer_key
GROUP BY country
ORDER BY quantity DESC;

